export type PermissionRequest = "ABSENCE_READ" | "ABSENCE_WRITE" | "ASSIGN_DATE" | "DAILY_NEWS_READ" | "DAILY_NEWS_WRITE" | "DEFAULT_VIEW_ACCESS" | "EVALUATION_READ" | "EVALUATION_WRITE" | "MEETING_ADVISOR" | "MEETINGS_READ" | "MEETINGS_WRITE" | "MONITORING_READ" | "MONITORING_WRITE" | "MOVE_TO_WIKI" | "MOVE_TO_WIKI" | "QUICKLINK_READ" | "QUICKLINK_WRITE" | "RECEIVE_TELEPHONE_NOTE" | "REMOVE_ASSIGNMENT" | "SEND_TELEPHONE_NOTE" | "USER_READ" | "USER_WRITE" | "VIEW_ACCESS_EVALUATION" | "VIEW_ACCESS_LOGIN" | "EVENT_TYPE_WRITE" | "EVENT_TYPE_READ" | "EVENT_INSTANCE_READ" | "EVENT_INSTANCE_WRITE" | "EVENT_MGMT_ASSIGNEE" | "VIEW_ACCESS_PORTFOLIO" | "WIKI_READ" | "MAIL_LOG" | "EXECUTE_CRONJOB" | "WIKI_WRITE" | string;

export interface Permission {
    id: string;
    description: string;
}

export interface PermissionRequestAccess {
    name: PermissionRequest,
    access: boolean
}